version: '2'
services:
  zen:
    build: .
    image: cd-zen-macro:latests
    env_file: ./cp-docker/docker.env
    ports:
      - "8000:8000"
    links:
      - db
    expose:
      - "5432"
    volumes:
      - ./workspace-zen:/usr/src/app/workspace-zen
  db:
    build: ./cp-docker
    image: cd-postgres:latest
  e2e:
    build: ./workspace-zen/cp-e2e-tests
    image: cd-e2e:latest
    links:
      - zen
